### ISSUE TITLE
Use Multi-line Comments

### ISSUE THREAD

**Issue by ZackAttack614** [prundstrom/Parker-s-Repository-of-Joyness#1]
https://github.com/prundstrom/Parker-s-Repository-of-Joyness/blob/6384e691fb0e6d76066ef755d1f794c2c3ba8ced/src/pe_1.py#L1-L5

To make it easier on yourself, consider using a [multi-line comment](https://stackoverflow.com/questions/7696924/way-to-create-multiline-comments-in-python):

```python
''' Problem 1:  Multiples of 3 and 5 

    If we list all the natural numbers below 10 that are multiples of 3 or 5,
    we get 3, 5, 6 and 9. The sum of these multiples is 23. 

    Find the sum of all the multiples of 3 or 5 below 1000. 
'''
```

**Comment by prundstrom** [comment]
sweet - will choose to make it easier on myself ;)
